"""empty message

Revision ID: 21cb5e5d5608
Revises: 685bcd66487c
Create Date: 2018-02-17 22:12:10.140237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cb5e5d5608'
down_revision = '685bcd66487c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'views')
    # ### end Alembic commands ###
