"""empty message

Revision ID: 685bcd66487c
Revises: 9bb00bf347d8
Create Date: 2018-02-05 11:39:46.407171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685bcd66487c'
down_revision = '9bb00bf347d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'image')
    op.drop_column('user', 'description')
    op.drop_column('entries', 'status')
    # ### end Alembic commands ###
