"""empty message

Revision ID: 93897622d936
Revises: 21cb5e5d5608
Create Date: 2018-02-22 20:28:08.708388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93897622d936'
down_revision = '21cb5e5d5608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('cover', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('facebook_id', sa.BigInteger(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user', 'facebook_id')
    op.drop_column('user', 'cover')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
