"""empty message

Revision ID: 9bb00bf347d8
Revises: 9fe6accf209c
Create Date: 2018-02-04 22:11:33.490648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb00bf347d8'
down_revision = '9fe6accf209c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('image', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('entries', 'image')
    # ### end Alembic commands ###
